version: '2'
jobs:
  build:
    docker:
    - image: docker:18.09.1
    environment:
      IMAGE_NAME: gcr.io/opensourcecoin/ipfs-test-network
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Build image
        command: |
          docker build . --tag "$IMAGE_NAME"
    - run:
        name: Test connection
        command: |
          docker run --detach --name ipfs "$IMAGE_NAME" --enable-pubsub-experiment

          time docker exec ipfs /app/wait-until-ready
          # Test if publishing works. It requires both peers to be
          # connected.
          docker exec ipfs ipfs name publish /ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv
          # Make sure that the option passed to `docker run` is picked
          # up properly
          docker exec ipfs ipfs pubsub pub foo bar
    - run:
        name: Collect container logs
        command: docker logs ipfs
        when: on_fail
    - run:
        name: Push image
        command: |
          if [[ "$CIRCLE_BRANCH" = "master" ]]; then
            # This key belongs to circleci-image-uploader@opensourcecoin.iam.gserviceaccount.com
            # The key ID is e7dd392d78a676d0d5bbe19ad5046aa2b9d91939
            docker login -u _json_key -p "$(echo $GCLOUD_SERVICE_KEY | base64 -d)" https://gcr.io
            docker push "$IMAGE_NAME"
          fi
